var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var e=0;return function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var e="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return e?e.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var e,b=[];!(e=a.next()).done;)b.push(e.value);return b};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,b){a!=Array.prototype&&a!=Object.prototype&&(a[e]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,e,b,d){if(e){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var c=a[d];c in b||(b[c]={});b=b[c]}a=a[a.length-1];d=b[a];e=e(d);e!=d&&null!=e&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var d=this;d instanceof String&&(d=String(d));var c=d.length;b=b||0;for(0>b&&(b=Math.max(b+c,0));b<c;b++){var e=d[b];if(e===a||Object.is(e,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,e,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},e=Object.create(new $jscomp.global.Proxy(a,{get:function(b,d,c){return b==a&&"q"==d&&c==e}}));return!0===e.q}catch(b){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,e){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(b){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(b||"")+"_"+e++,b)}var e=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.owns=function(a,e){return Object.prototype.hasOwnProperty.call(a,e)};
$jscomp.polyfill("WeakMap",function(a){function e(){if(!a||!Object.seal)return!1;try{var f=Object.seal({}),d=Object.seal({}),b=new a([[f,2],[d,3]]);if(2!=b.get(f)||3!=b.get(d))return!1;b.delete(f);b.set(d,4);return!b.has(f)&&4==b.get(d)}catch(h){return!1}}function b(){}function d(a){if(!$jscomp.owns(a,g)){var f=new b;$jscomp.defineProperty(a,g,{value:f})}}function c(a){var f=Object[a];f&&(Object[a]=function(a){if(a instanceof b)return a;d(a);return f(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&
$jscomp.ES6_CONFORMANCE)return a}else if(e())return a;var g="$jscomp_hidden_"+Math.random();c("freeze");c("preventExtensions");c("seal");var k=0,l=function(a){this.id_=(k+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var f;!(f=a.next()).done;)f=f.value,this.set(f[0],f[1])}};l.prototype.set=function(a,b){d(a);if(!$jscomp.owns(a,g))throw Error("WeakMap key fail: "+a);a[g][this.id_]=b;return this};l.prototype.get=function(a){return $jscomp.owns(a,g)?a[g][this.id_]:void 0};l.prototype.has=
function(a){return $jscomp.owns(a,g)&&$jscomp.owns(a[g],this.id_)};l.prototype.delete=function(a){return $jscomp.owns(a,g)&&$jscomp.owns(a[g],this.id_)?delete a[g][this.id_]:!1};return l},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function e(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),b=new a($jscomp.makeIterator([[f,"s"]]));if("s"!=b.get(f)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var d=b.entries(),c=d.next();if(c.done||c.value[0]!=f||"s"!=c.value[1])return!1;c=d.next();return c.done||4!=c.value[0].x||"t"!=c.value[1]||!d.next().done?!1:!0}catch(q){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(e())return a;$jscomp.initSymbolIterator();var b=new WeakMap,d=function(a){this.data_={};this.head_=k();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};d.prototype.set=function(a,b){a=0===a?0:a;var d=c(this,a);d.list||(d.list=this.data_[d.id]=[]);d.entry?d.entry.value=b:(d.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:b},d.list.push(d.entry),this.head_.previous.next=d.entry,this.head_.previous=d.entry,this.size++);return this};d.prototype.delete=function(a){a=c(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=k();this.size=0};d.prototype.has=function(a){return!!c(this,a).entry};
d.prototype.get=function(a){return(a=c(this,a).entry)&&a.value};d.prototype.entries=function(){return g(this,function(a){return[a.key,a.value]})};d.prototype.keys=function(){return g(this,function(a){return a.key})};d.prototype.values=function(){return g(this,function(a){return a.value})};d.prototype.forEach=function(a,b){for(var d=this.entries(),c;!(c=d.next()).done;)c=c.value,a.call(b,c[1],c[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var c=function(a,d){var c=d&&typeof d;"object"==
c||"function"==c?b.has(d)?c=b.get(d):(c=""+ ++l,b.set(d,c)):c="p_"+d;var e=a.data_[c];if(e&&$jscomp.owns(a.data_,c))for(a=0;a<e.length;a++){var f=e[a];if(d!==d&&f.key!==f.key||d===f.key)return{id:c,list:e,index:a,entry:f}}return{id:c,list:e,index:-1,entry:void 0}},g=function(a,d){var b=a.head_;return $jscomp.iteratorPrototype(function(){if(b){for(;b.head!=a.head_;)b=b.previous;for(;b.next!=b.head;)return b=b.next,{done:!1,value:d(b)};b=null}return{done:!0,value:void 0}})},k=function(){var a={};return a.previous=
a.next=a.head=a},l=0;return d},"es6","es3");
$jscomp.polyfill("Set",function(a){function e(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([b]));if(!c.has(b)||1!=c.size||c.add(b)!=c||1!=c.size||c.add({x:4})!=c||2!=c.size)return!1;var e=c.entries(),k=e.next();if(k.done||k.value[0]!=b||k.value[1]!=b)return!1;k=e.next();return k.done||k.value[0]==b||4!=k.value[0].x||k.value[1]!=k.value[0]?!1:e.next().done}catch(l){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(e())return a;$jscomp.initSymbolIterator();var b=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};b.prototype.add=function(a){a=0===a?0:a;this.map_.set(a,a);this.size=this.map_.size;return this};b.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};b.prototype.clear=function(){this.map_.clear();
this.size=0};b.prototype.has=function(a){return this.map_.has(a)};b.prototype.entries=function(){return this.map_.entries()};b.prototype.values=function(){return this.map_.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(a,b){var c=this;this.map_.forEach(function(d){return a.call(b,d,d,c)})};return b},"es6","es3");
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push(a[d]);return b}},"es8","es3");var executionContext=this;
(function(a){(a.SafeWeb=a.SafeWeb||{}).constants={SHASTA_URL:"https://ratings-wrs.norton.com",SHASTA_LOOKUP_PATH:"brief",DEFAULT_FULL_REPORT_URL:"https://safeweb.norton.com/report/show",HTTP_PROTOCOL:"http",HTTPS_PROTOCOL:"https",HTTPS_GET_METHOD:"GET",HTTPS_POST_METHOD:"POST",PII_SUBMISSION_TIMEOUT:2E3,SCAM_INSIGHT_BLOCK_PAGE_PATH:"content/ui/scam-insight-block-page.html",BLOCK_PAGE_PATH:"content/ui/blockedPage.html",SYMC_USER_AGENT:"X-Symc-User-Agent",X_NLOK_COUNTRY:"X-NLOK-COUNTRY",WRS_HEADER_VALUES:{XBP_SAFEWEB:"xBP/SafeWeb",
XBP_SAFEWEB_YAHOO:"xBP/SafeWeb_Yahoo",XBP_SAFEWEB_YAHOO_ADVT:"xBP/SafeWeb_Yahoo_Advt"},JAPAN_LOCALE:"ja",ROOT_NODE:{TAG_NAME:"symantec",VERSION_ATTR:"v",CACHE_POSITIVE_ATTR:"cacheP",CACHE_NEGATIVE_ATTR:"cacheN"},PII_FLAGS:{EXIT_SITE:0,CONTINUE_TO_SITE:1,SUPPRESSED_DUE_TO_SILENTMODE:2,SUPPRESSED_DUE_TO_HTTPS:4},PII_SUBMISSION_STATUS:{SUCCESS:"Success",FAILURE:"Fail"},SITE_NODE:{TAG_NAME:"site",CANONICAL_SITE_ID_ATTR:"id",COMBINED_RATING_ATTR:"r",SECURITY_RATING_ATTR:"sr",BUSINESS_RATING_ATTR:"br",
CATEGORY_ATTR:"category",CACHE_ATTR:"cache",PII_ENABLE_ATTR:"piien",PII_POLICY_HTTPS:"piipolhttps",PII_POLICY_ID:"piipolid",PII_POLICY_FIELD_TYPE:"piipolft"},WRS_RATINGS:{UNKNOWN_SITE:"u",BAD_SITE:"b",WARNING_SITE:"w",GOOD_SITE:"g",NORTON_SECURE_SITE:"r",PII_NOT_ENABLED:"n",PII_ENABLED:"y",PII_SILENCE:"s",REGIONAL_BLOCK:"grbl"},ANNOYANCE_FACTORS_KEYS:{PUAPP:!0,HRDUN:!0,JOKE:!0,MLAPP:!0,TRCKW:!0,TPSQT:!0,PPCNA:!0,HACK:!0,SPAM:!0,SWBPL:!0},PII_FACTORS_KEYS:{PIIAGE:"age",PIIPOP:"pop"},PII_POLICY_HTTPS_KEYS:{DONTCARE:"dc",
HTTPS:"h"},IDENTITY_THREATS_KEYS:{MLWR:!0,MBCHG:!0,RMTA:!0,PHISH:!0,BDOOR:!0,ISTLR:!0,DIAL:!0,DLDR:!0,SPWR:!0},SHOPPING_RISKS_KEYS:{CTFGS:!0,RCGS:!0,REPLC:!0},COMPUTER_THREATS_KEYS:{COHD:!0,ADWR:!0,VIRUS:!0,WORM:!0,SRISK:!0,BREXP:!0,MLWR:!0,MBCHG:!0,HEUR:!0,ELTMS:!0,TRJN:!0},SITE_FACT_NODE:{TAG_NAME:"d",REPORTED_BY_KEY:"reported_by",SRC_KEY:"src",ID_KEY:"id"},SITE_FACT_IDS:{PRIVACY_POLICY_APPROVED:"privacy policy approved",NETWORK_SCANNING_SERVICE:"network scanning service",SSL_CA_NAME:"ssl CA name",
AUTHORIZED_RESELLER:"Authorized Reseller",CERTIFIED_BUSINESS:"certified business",VERISIGN_TRUSTED:"VRTRU",VERISIGN_SSL:"VRSSL"},SITE_FACT_SOURCES:{SRC_BUYSAFE:"BUYSAFE",SRC_VERISIGN:"Verisign",SRC_MARK_MONITOR:"MARKMONITOR"},ATTRIBUTE_COUNT:"cnt",CACHE_LIMIT:1E3,RATING_TYPE:{WCID_HEURISTICS:1,WCID_CHECK_URL:2,SAFEWEB:3,SCAM_INSIGHT:4},MESSAGES:{WAX_FIELDS_FOUND:"45E6BAD1-9F79-4E16-BA3A-1F77AA21EAC9",PROCESS_PAGE_FOR_SCAM_FIELDS:"FEDA41BC-73DC-4F99-A2CF-B5589CF2D0F8",TOP_FRAME_UNLOADED:"E5C199FF-A74B-414F-803C-4C7030C0E573",
CAN_ANALYZE_FOR_SCAM:"6E6CDFB7-4CF6-4C73-B998-6CA3432DDC07"},IS_SCAM_INSIGHT_ENABLED:!0,performanceReporter:{COMPONENT:{SCAM_INSIGHT:"scam_insight"},TYPE:{INIT:"init",PII_PROTO_SUBMISSION:"_piiProtoSubmission",CALCULATE_SCAM_RATING:"_calculateScamInsightRating",HANDLE_PII_RATING:"_handlePIIEnabledRating",SET_WRS_RESPONSE:"setWrsResponse",HANDLE_MESSAGE:"_handleMessage",HANDLE_MESSAGE_CALLBACK:"_handleScamPageFoundCallback",HANDLE_CACHE_RESPONSE:"_handleCacheResponse",SEND_PII_SUBMISSION:"sendPIISubmission",
COLLECT_PII_FIELDS:"_collectPIIFields",TOP_FRAME_UNLOADED:"topFrameUnloaded",ADD_MUTATION_OBSERVER:"_addBodyMutationObserver",FIELD_FOUND_CALLBACK:"handleFieldsFoundCallback",WAX_CONTROLLER_INITIALIZE:"scamInsightWaxControllerInitialize",CAN_ANALYZE_HANDLER_RESPONSE:"canAnalyzeForScamHandlerResponse",RUN_WAX_ANALYSIS:"_runWaxAnalysis"}},SCAM_INSIGHT_RESULT:{UNTESTED:0,SUSPICIOUS_PAGE:1,SUSPICIOUS_NO_BLOCK_PAGE:2,NOT_SUSPICIOUS_PAGE:3},SCAM_INSIGHT_RATING_KEY:"scamRating",SCAM_ANALYSIS_STATE:{PENDING:0,
ANALYZE:1},YAHOO_DOMAIN:"yahoo.com",HSPART_KEY:"hspart",HSPART_VALUE:["symantec","norton"]}})(executionContext);
(function(a){(a.SafeWeb=a.SafeWeb||{}).scamInsightWaxController=function(a){var b=SymWax.main,d=a.extensionAdapter,c=SafeWeb.constants,e=SymWax.constants,k=a.utils.isntNil,l=a.utils.isNil,f=a.utils.isArray,r=a.logger,m=a.performanceReporterFactoryProxy,h={_runWaxAnalysis:function(){var f=c.performanceReporter.TYPE.RUN_WAX_ANALYSIS+":"+Date.now();m.reportStart(c.performanceReporter.COMPONENT.SCAM_INSIGHT,f);h.arrPIIFields=[];h._bodyObserver=null;b.registerFieldsFoundCallback(h.handleFieldsFoundCallback,
e.fieldFilter.type.CATEGORIZED_INPUT_FIELDS);b.registerFormsFound(function(){});b.initWithThreshold(function(a){!0===a&&r.debug("Current frame has been accepted for Wax Analysis")});a.utils.isTopLevelWindow()&&window.addEventListener("beforeunload",function(){d.sendMessage({id:c.MESSAGES.TOP_FRAME_UNLOADED})},!0);m.reportEnd(c.performanceReporter.COMPONENT.SCAM_INSIGHT,f)},handleFieldsFoundCallback:function(a){if(f(a)&&!(0>=a.length)){var b=c.performanceReporter.TYPE.FIELD_FOUND_CALLBACK+":"+Date.now();
m.reportStart(c.performanceReporter.COMPONENT.SCAM_INSIGHT,b);var g=[],l=!0,q;for(q in a){var n=e.fieldTypeToPIIIdentifiers[a[q].getFieldType()],p=e.fieldTypeToPIIIdentifiers[a[q].getPreGroupFieldType()];k(n)&&!g.includes(n)&&(g.push(n),h.arrPIIFields.includes(n)||(l=!1));k(n)&&k(p)&&n!==p&&!g.includes(p)&&(g.push(p),h.arrPIIFields.includes(p)||(l=!1))}!1===l&&(h.arrPIIFields=[].concat($jscomp.arrayFromIterable(new Set([].concat($jscomp.arrayFromIterable(h.arrPIIFields),$jscomp.arrayFromIterable(g))))),
r.debug(h.arrPIIFields),d.sendMessage({id:c.MESSAGES.WAX_FIELDS_FOUND,data:h.arrPIIFields}));m.reportEnd(c.performanceReporter.COMPONENT.SCAM_INSIGHT,b)}},handleMessage:function(a,b,d){if(!l(a)&&!l(a.id)){b=c.performanceReporter.TYPE.HANDLE_MESSAGE_CALLBACK+":"+Date.now();m.reportStart(c.performanceReporter.COMPONENT.SCAM_INSIGHT,b);switch(a.id){case c.MESSAGES.PROCESS_PAGE_FOR_SCAM_FIELDS:a.state===c.SCAM_ANALYSIS_STATE.ANALYZE&&h._analysisState===c.SCAM_ANALYSIS_STATE.PENDING&&(h._runWaxAnalysis(),
h._analysisState=c.SCAM_ANALYSIS_STATE.ANALYZE)}m.reportEnd(c.performanceReporter.COMPONENT.SCAM_INSIGHT,b)}},initialize:function(){if(SafeWeb.constants.IS_SCAM_INSIGHT_ENABLED){var a=c.performanceReporter.TYPE.WAX_CONTROLLER_INITIALIZE+":"+Date.now();m.reportStart(c.performanceReporter.COMPONENT.SCAM_INSIGHT,a);h._analysisState=c.SCAM_ANALYSIS_STATE.PENDING;d.addContentScriptMessageListener(h.handleMessage);d.sendMessage({id:c.MESSAGES.CAN_ANALYZE_FOR_SCAM},function(a){var b=c.performanceReporter.TYPE.CAN_ANALYZE_HANDLER_RESPONSE+
":"+Date.now();m.reportStart(c.performanceReporter.COMPONENT.SCAM_INSIGHT,b);l(a)||-1===Object.values(c.SCAM_ANALYSIS_STATE).indexOf(a)||(h._analysisState=a,h._analysisState===c.SCAM_ANALYSIS_STATE.ANALYZE&&h._runWaxAnalysis(),m.reportEnd(c.performanceReporter.COMPONENT.SCAM_INSIGHT,b))});m.reportEnd(c.performanceReporter.COMPONENT.SCAM_INSIGHT,a)}}};window.addEventListener("load",h.initialize,!0);return h}(a.SymBfw)})(executionContext);
